"""Far Manager's UI strings → Fluent files.

Far keeps all its translations in far/farlang.templ.m4: a message id, then
optional comment lines (`l:...`), then one quoted line per language in the
order of the header. `upd:` marks a line that was not translated yet (it
holds English); such lines are skipped so the English fallback is used.

    python tools/far_lng.py find <text>              ids whose Russian or English text contains <text>
    python tools/far_lng.py gen <ids.txt> <out-dir>  write <out-dir>/<lang>.ftl for every language

Far's strings are © Far Group, BSD 3-Clause (see docs/07-far-reference.md).
"""

import re
import sys
from pathlib import Path

SOURCE = Path(__file__).resolve().parent.parent / "FarManager" / "far" / "farlang.templ.m4"
# Order of the languages in farlang.templ.m4 (its header) and their codes.
LANGS = ["ru", "en", "cs", "de", "hu", "pl", "es", "sk", "it", "uk", "be", "lt", "pt"]


def parse(path=SOURCE):
    """{id: [text or None per language]}."""
    lines = path.read_text(encoding="utf-8-sig").splitlines()
    out = {}
    i = 0
    ident = re.compile(r"^M[A-Za-z0-9_]+$")
    while i < len(lines):
        if not ident.match(lines[i]):
            i += 1
            continue
        mid = lines[i]
        i += 1
        texts = []
        while i < len(lines) and len(texts) < len(LANGS):
            line = lines[i]
            if line.startswith("l:") or line.startswith("#"):
                i += 1
                continue
            stale = line.startswith("upd:")
            if stale:
                line = line[4:]
            if not (line.startswith('"') and line.endswith('"')):
                break
            text = line[1:-1].replace('\\"', '"').replace("\\\\", "\\")
            texts.append(None if stale else text)
            i += 1
        if len(texts) == len(LANGS):
            out[mid] = texts
    return out


def to_fluent(text):
    """A Far string as a Fluent pattern: {0} → { $p0 }, other braces and
    significant leading/trailing whitespace escaped."""
    parts = []
    pos = 0
    for m in re.finditer(r"\{(\d+)\}|[{}]", text):
        parts.append(text[pos:m.start()])
        if m.group(1) is not None:
            parts.append("{ $p" + m.group(1) + " }")
        else:
            parts.append('{ "' + m.group(0) + '" }')
        pos = m.end()
    parts.append(text[pos:])
    s = "".join(parts)
    if s == "":
        return '{ "" }'
    # Fluent trims leading whitespace and treats [ * . specially at the start.
    lead = len(s) - len(s.lstrip(" "))
    if lead:
        s = '{ "' + " " * lead + '" }' + s[lead:]
    elif s[0] in "[*.":
        s = '{ "' + s[0] + '" }' + s[1:]
    trail = len(s) - len(s.rstrip(" "))
    if trail:
        s = s[: len(s) - trail] + '{ "' + " " * trail + '" }'
    return s


def cmd_find(text):
    for mid, texts in parse().items():
        ru, en = texts[0] or "", texts[1] or ""
        if text.lower() in ru.lower() or text.lower() in en.lower():
            print(f"{mid}\t{ru}\t|\t{en}")


def cmd_gen(ids_file, out_dir):
    data = parse()
    ids = [
        line.split("#")[0].strip()
        for line in Path(ids_file).read_text(encoding="utf-8").splitlines()
    ]
    ids = [i for i in ids if i]
    missing = [i for i in ids if i not in data]
    if missing:
        sys.exit(f"unknown ids: {missing}")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for n, lang in enumerate(LANGS):
        lines = [
            "# Generated by tools/far_lng.py from FarManager/far/farlang.templ.m4.",
            "# Far Manager strings © Far Group, BSD 3-Clause. Do not edit by hand.",
            "",
        ]
        for mid in ids:
            text = data[mid][n]
            if text is not None:
                lines.append(f"{mid} = {to_fluent(text)}")
        # LF, as .gitattributes keeps the repository.
        (out / f"{lang}.ftl").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(ids)} ids → {len(LANGS)} languages in {out}")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    if len(sys.argv) >= 3 and sys.argv[1] == "find":
        cmd_find(" ".join(sys.argv[2:]))
    elif len(sys.argv) == 4 and sys.argv[1] == "gen":
        cmd_gen(sys.argv[2], sys.argv[3])
    else:
        print(__doc__)
