//! Localization with Fluent (https://projectfluent.org).
//!
//! Strings live in `i18n/<lang>.ftl` (afar's own) and `i18n/far/<lang>.ftl`
//! (Far Manager's, generated by tools/far_lng.py from Far's language file);
//! both are embedded in the binary. The language is `AFAR_LANG`, otherwise
//! the Windows UI language, otherwise English; a string missing in the
//! chosen language falls back to English.
//!
//! What the agent reads (MCP tools, the journal, the system prompt) stays
//! in English and does not go through here.

use std::sync::OnceLock;

use fluent_bundle::concurrent::FluentBundle;
use fluent_bundle::{FluentArgs, FluentResource};
use unic_langid::LanguageIdentifier;

struct Lang {
    code: &'static str,
    afar: &'static str,
    far: &'static str,
}

macro_rules! lang {
    ($code:literal, afar) => {
        Lang {
            code: $code,
            afar: include_str!(concat!("../i18n/", $code, ".ftl")),
            far: include_str!(concat!("../i18n/far/", $code, ".ftl")),
        }
    };
    ($code:literal) => {
        Lang {
            code: $code,
            afar: "",
            far: include_str!(concat!("../i18n/far/", $code, ".ftl")),
        }
    };
}

/// English first: it is the fallback.
const LANGS: &[Lang] = &[
    lang!("en", afar),
    lang!("ru", afar),
    lang!("cs"),
    lang!("de"),
    lang!("hu"),
    lang!("pl"),
    lang!("es"),
    lang!("sk"),
    lang!("it"),
    lang!("uk"),
    lang!("be"),
    lang!("lt"),
    lang!("pt"),
];

pub struct Catalog {
    code: &'static str,
    bundle: FluentBundle<FluentResource>,
    fallback: FluentBundle<FluentResource>,
}

fn bundle(lang: &Lang) -> FluentBundle<FluentResource> {
    let id: LanguageIdentifier = lang.code.parse().expect("language code");
    let mut bundle = FluentBundle::new_concurrent(vec![id]);
    // No Unicode isolation marks around arguments: a terminal shows them.
    bundle.set_use_isolating(false);
    for source in [lang.afar, lang.far] {
        if source.is_empty() {
            continue;
        }
        let resource = FluentResource::try_new(source.to_string()).unwrap_or_else(|(r, errors)| {
            debug_assert!(errors.is_empty(), "{}: {errors:?}", lang.code);
            r
        });
        if let Err(errors) = bundle.add_resource(resource) {
            debug_assert!(errors.is_empty(), "{}: {errors:?}", lang.code);
        }
    }
    bundle
}

impl Catalog {
    pub fn new(code: &str) -> Self {
        let lang = LANGS.iter().find(|l| l.code == code).unwrap_or(&LANGS[0]);
        Self {
            code: lang.code,
            bundle: bundle(lang),
            fallback: bundle(&LANGS[0]),
        }
    }

    pub fn code(&self) -> &'static str {
        self.code
    }

    pub fn get(&self, id: &str, args: Option<&FluentArgs>) -> String {
        for bundle in [&self.bundle, &self.fallback] {
            if let Some(pattern) = bundle.get_message(id).and_then(|m| m.value()) {
                let mut errors = Vec::new();
                return bundle
                    .format_pattern(pattern, args, &mut errors)
                    .into_owned();
            }
        }
        // A missing string shows itself rather than nothing.
        id.to_string()
    }
}

/// The language to use: `AFAR_LANG`, the system UI language, English.
pub fn detect() -> String {
    detect_with("")
}

/// The language to use: `AFAR_LANG`, `configured` (the setting, if not
/// empty), the system UI language, English.
pub fn detect_with(configured: &str) -> String {
    let wanted = std::env::var("AFAR_LANG")
        .ok()
        .filter(|l| !l.is_empty())
        .or_else(|| (!configured.is_empty()).then(|| configured.to_string()))
        .or_else(sys_locale::get_locale)
        .unwrap_or_default();
    let primary = wanted
        .split(['-', '_', '.'])
        .next()
        .unwrap_or("")
        .to_ascii_lowercase();
    if LANGS.iter().any(|l| l.code == primary) {
        primary
    } else {
        "en".into()
    }
}

static CATALOG: OnceLock<Catalog> = OnceLock::new();

/// Chooses the language (once, at start-up); later calls are ignored.
pub fn init(code: &str) {
    let _ = CATALOG.set(Catalog::new(code));
}

fn catalog() -> &'static Catalog {
    CATALOG.get_or_init(|| Catalog::new(&detect()))
}

pub fn lang() -> &'static str {
    catalog().code()
}

pub fn tr(id: &str) -> String {
    catalog().get(id, None)
}

pub fn tr_args(id: &str, args: &FluentArgs) -> String {
    catalog().get(id, Some(args))
}

/// `tr!("id")` or `tr!("id", name = value, …)`.
#[macro_export]
macro_rules! tr {
    ($id:expr) => {
        $crate::i18n::tr($id)
    };
    ($id:expr, $($key:ident = $value:expr),+ $(,)?) => {{
        let mut args = fluent_bundle::FluentArgs::new();
        $(args.set(stringify!($key), $value);)+
        $crate::i18n::tr_args($id, &args)
    }};
}

/// Far's ending of "N item(s)" (copy.cpp): `MCMLItems0` after 1,
/// `MCMLItemsS` after 0, 5–9 and 10–19, `MCMLItemsA` otherwise — the rule is
/// Russian, the endings come from the language file.
pub fn far_items_suffix(n: usize) -> String {
    let s = n.to_string();
    let b = s.as_bytes();
    let last = b[b.len() - 1];
    let id = if (b.len() >= 2 && b[b.len() - 2] == b'1') || last >= b'5' || last == b'0' {
        "MCMLItemsS"
    } else if last == b'1' {
        "MCMLItems0"
    } else {
        "MCMLItemsA"
    };
    tr(id)
}

/// Decimal separator of the interface language (until numbers follow the
/// Windows regional settings, as in Far).
pub fn decimal_separator() -> &'static str {
    if lang() == "en" { "." } else { "," }
}

/// Removes Far's hotkey markers (`&`) from a label.
pub fn plain(s: &str) -> String {
    s.replace('&', "")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(pairs: &[(&'static str, usize)]) -> FluentArgs<'static> {
        let mut a = FluentArgs::new();
        for (k, v) in pairs {
            a.set(*k, *v);
        }
        a
    }

    #[test]
    fn every_language_parses_and_has_far_strings() {
        for l in LANGS {
            let c = Catalog::new(l.code);
            assert_eq!(c.code(), l.code);
            assert_ne!(c.get("MCopyDlgTitle", None), "MCopyDlgTitle", "{}", l.code);
        }
    }

    #[test]
    fn russian_and_english_with_arguments_and_plurals() {
        let ru = Catalog::new("ru");
        let en = Catalog::new("en");
        assert_eq!(ru.get("MCopyDlgTitle", None), "Копирование");
        assert_eq!(en.get("MCopyDlgTitle", None), "Copy");
        let a = args(&[("p0", 3)]);
        assert_eq!(ru.get("MAskDeleteAndMore", Some(&a)), "…и ещё 3");
        let n = |k| args(&[("count", k)]);
        assert_eq!(ru.get("objects", Some(&n(1))), "1 объект");
        assert_eq!(ru.get("objects", Some(&n(3))), "3 объекта");
        assert_eq!(ru.get("objects", Some(&n(11))), "11 объектов");
        assert_eq!(en.get("objects", Some(&n(1))), "1 object");
        assert_eq!(en.get("objects", Some(&n(2))), "2 objects");
        // Missing in a language: English; missing everywhere: the id.
        assert_eq!(
            Catalog::new("de").get("agent-running", None),
            en.get("agent-running", None)
        );
        assert_eq!(ru.get("no-such-string", None), "no-such-string");
    }

    #[test]
    fn far_leading_spaces_survive() {
        // Far's MListFileSize has no padding, but braces must be literal
        // where Far uses them; sanity-check a formatted string.
        let ru = Catalog::new("ru");
        let a = {
            let mut a = FluentArgs::new();
            a.set("p0", "1 234");
            a.set("p1", 2);
            a.set("p2", 3);
            a
        };
        assert_eq!(
            ru.get("MListFileSize", Some(&a)),
            "Байт: 1 234, файлов: 2, папок: 3"
        );
    }
}
